### ISSUE TITLE
Dual Sim card may not work .

### ISSUE THREAD

**Issue by iocoo** [GhostFlying/LocationReportEnabler#10] opened 2015-03-18 01:51 UTC
双卡不起作用，麻烦确认，谢谢！

**Comment by GhostFlying** [comment] 2015-03-20 07:38
I've no phone with dual sim so that I can hardly confirm the problem, do you give me more info?

**Comment by ermalx** [comment] 2015-05-05 11:32
I have LG Pro Lite Dual and it works perfectly.

**Comment by simonsmh** [comment] 2016-12-15 13:28
setprop gsm.sim.operator.iso-country "us,us"
setprop gsm.sim.operator.numeric "310004,310004"
@GhostFlying 这样可以就兼容双卡了

**Comment by GhostFlying** [comment] 2016-12-15 13:38
Thx, I will try it soon.

**Comment by simonsmh** [comment] 2016-12-16 00:00
I made it a dual sim version. Will it work on single sim devices? Or side effects?
https://github.com/simonsmh/LocationReportEnabler/raw/master/outputs/apk/app-release-unsigned.apk

**Comment by GhostFlying** [comment] 2016-12-16 11:46
Thx, I will try to test it.

**Comment by simonsmh** [comment] 2016-12-17 16:22
我对Java很陌生，所以抱歉只能用shell作演示
用`getprop|grep gsm.sim.state|grep ","`判断或许比设备型号好。
```
$ getprop|grep gsm.sim.state|grep ","
[gsm.sim.state]: [READY,ABSENT]
```

**Comment by GhostFlying** [comment] 2016-12-17 16:23
实际上现在应该有 API 可以判断，我会测试下和直接读变量哪个更合适。

**Comment by dlhxr** [comment] 2016-12-17 17:45
FYI
https://github.com/dlhxr/LocationReportEnabler/commits/dual-sim

**Comment by dlhxr** [comment] 2016-12-19 12:25
Something interesting i found today. I set the operator to 310030,310004 last night and I just found the location report was disabled. Then I changed back to 310004,310004 and reboot. I could enable the location report again. Don't know why....I doubt whether google is blocking 310030 operator, though it seems impossible

**Comment by dlhxr** [comment] 2016-12-19 12:26
plus I use China Telecom. And i have to reset the apn once I reboot to get access to data. No idea why...( Xposed mod worked fine, but I upgraded to 7.0 two weeks ago...)

**Comment by GhostFlying** [comment] 2016-12-19 12:31
It seems no reason to block the 310030 and this code works well in lots of devices with single sim card.

Fake operator code may cause some APN errors as the order of APN setting init and gms read info can not be confirmed and may change by many uncontrolled causes. Xposed one is always the best way but..

**Comment by GhostFlying** [comment] 2016-12-19 13:40
well, I made some fix about this and u can try it from the release page or compile by yourself.

wish it works well and thanks for ur help.

**Comment by dlhxr** [comment] 2016-12-19 14:02
haha, thank you for your effort. I think i should fix my sms first... Since I upgrade to 7.0 with the non-xposed version. I haven't received any sms yet. After i remove the app, the symptom was still there...I could only send msg, but can't receive any.

**Comment by simonsmh** [comment] 2016-12-19 14:05
Check it by running `getprop` in terminal and look up for the tile begin
with gsm.

Hoary <notifications@github.com>于2016年12月19日周一 下午10:02写道：

**Comment by dlhxr** [comment] 2016-12-19 14:07
it went back to normal, but still can't receive any sms...
might due to many reasons, trying to figure it out.

**Comment by simonsmh** [comment] 2016-12-19 14:15
卡里没钱了？
打个10000问问呗

Hoary <notifications@github.com>于2016年12月19日周一 下午10:07写道：

**Comment by simonsmh** [comment] 2016-12-19 14:48
@GhostFlying Would you please make operator code editable?
Btw you can manually close this issue.

**Comment by GhostFlying** [comment] 2016-12-19 14:50
I will consider that and u can open a new issue about that :).

**Closed by GhostFlying** 2016-12-19 14:50 UTC
